<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find fishbot_description)/urdf/fishbot/common_inertia.xacro"/>

    <link name="base_footprint"/>
    <!--    机器人的身体部分-->
    <xacro:macro name="base_xacro" params="length radius">
        <link name="base_link">
            <!-- 部件的外观描述-->
            <visual>
                <!-- 沿着自己几何中心的偏移和旋转-->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- 几何形状-->
                <geometry>
                    <!-- 圆柱体 radius半径 高度 length-->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!--            材质颜色-->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </visual>
            <!--        碰撞属性-->
            <collision>
                <!-- 沿着自己几何中心的偏移和旋转-->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- 几何形状-->
                <geometry>
                    <!-- 圆柱体 radius半径 高度 length-->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!--            材质颜色-->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}"/>
        </link>
        <joint name="base_joint" type="fixed">
            <origin xyz="0 0 ${length/2+0.032-0.001}" rpy="0.0 0.0 0.0"/>
            <parent link="base_footprint"/>
            <child link="base_link"/>
        </joint>
    </xacro:macro>
</robot>